### ISSUE TITLE
I think I'm doing something wrong...

### ISSUE THREAD

**Issue by guidouil** [jonblum/meteor-cropper#1]
Here is the meteorpad where I reproduce my bug.
http://meteorpad.com/pad/aFZ2Z2p4Q7eYHg925/Image%20Cropper%20Demo
Can you throw me a bone ?

**Comment by guidouil** [comment]
@jonblum can you publish a little example on how to use meteor-cropper in a meteor project ?
The example on the source website are great but there is no explanation on how to use with Meteor and it's events and helpers...

**Comment by jonblum** [comment]
The plugin has some issues when the image source is set dynamically, particularly in a modal.  Try explicitly setting the source before you load the cropper in the modal show event:

``` javascript
$('.imgtocropp').attr("src",Session.get('imgtocropp'));
$('.imgtocropp').cropper({ ...
```

I've been meaning to make a more Meteoric wrapper template for the plugin to handle cases like this...

**Comment by guidouil** [comment]
Copy / past ... rocking :)
Thanks great help.
Now you can add two example to your readme 
Basic : 
http://meteorpad.com/pad/SuQSLbtsc5MvrxFJC/CropTest
and in popup with upload :
http://meteorpad.com/pad/aFZ2Z2p4Q7eYHg925/Image%20Cropper%20Demo
