### ISSUE TITLE
Fixed/Resizeable Crop Box Not Working

### ISSUE THREAD

**Issue by boblikesoup** [jonblum/meteor-cropper#5]
Hi I got your plugin working except fixed cropper isn't working like in the demo with all the same attributes.  The aspect ratio is working but all the dragging/moveable/resizable aren't.  I think you need to update the library because this feature was added in June and the last update here was in May.

Template.createPostCrop.onRendered ->
  $(".cropper-example-1 > img").cropper
    aspectRatio: 3 / 4
    autoCropArea: 0.65
    strict: false
    guides: false
    highlight: false
    dragCrop: false
    cropBoxMovable: false
    cropBoxResizable: false

**Comment by jonblum** [comment]
Hi John – yep, looks like this package was behind a version.  Sorry about that!  Give it a shot with 0.10.0 and let me know if that does the trick.
