### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by jxm262** [jonblum/meteor-cropper#6]
Hey, sorry for posting this as an issue as I think it's more of a feature request.  Do you mind if I add some examples to the readme?  I just spent a decent amount of frustrating time trying to get an example working - since I wasn't sure what to look for.  I realize the examples are more for the actual jquery cropper library (my frustrations are not with your plugin :)  But I think it would be a good idea to have a few quick examples with some meteor templates and possibly even a quick demo uploading an image to a server.  

Mind if I issue a PR for this?  Let me know and I'll update the Readme and add a couple examples.

**Comment by jonblum** [comment]
Before you go to that trouble, what did you have in mind?  I don't think there's anything meteor-specific about using the plugin...  this is just a wrapper.

**Comment by jxm262** [comment]
Yeah you're right.  Took a look after I sent that message and realized all it does is wrap the jquery cropper js file.  I had some issues getting it to work which I thought was this plugin at first, then realized it was actually with the wrapped library.  Can close this issue, thanks for responding :)

**Comment by jonblum** [comment]
FWIW, if/when Cropper stabilizes at a 1.0, I've thought about adding more Meteor-specific shortcuts and functionality ( `{{> cropper img=reactiveVar}}` or the like).

**Comment by jxm262** [comment]
@jonblum  yeah that actually sounds like a good idea.  Maybe even make some 'plugin' type of functionality (perhaps on a separate project, not sure..) similar to how the meteor-useraccounts/core package works.  Anyway, let me know if you'd like any help or have any ideas.
