### ISSUE TITLE
Cropper takes over full width of screen but retains image height. How do you prevent cropper from taking over full screen width?

### ISSUE THREAD

**Issue by Blenditlikeben** [jonblum/meteor-cropper#8]

**Comment by jonblum** [comment]
Hard to say exactly without seeing your code, but in general, the cropper fills its surrounding div.  From [the docs](https://github.com/fengyuanchen/cropper):

> The size of the cropper inherits from the size of the image's parent element (wrapper), so be sure to wrap the image with a visible block element.
